version: 2.1

orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          dockerfile: udagram-api-user/Dockerfile
          image: ahmadsherief/udagram-api-user
          tag: "latest"
          path: udagram-api-user
      - docker/publish:
          dockerfile: udagram-api-feed/Dockerfile
          image: ahmadsherief/udagram-api-feed
          tag: "latest"
          path: udagram-api-feed
      - docker/publish:
          dockerfile: udagram-frontend/Dockerfile
          image: ahmadsherief/udagram-frontend:local
          tag: "latest"
          path: udagram-frontend
      - docker/publish:
          dockerfile: udagram-reverseproxy/Dockerfile
          image: ahmadsherief/reverseproxy
          tag: "latest"
          path: udagram-reverseproxy
